### ISSUE TITLE
Error on ./update.sh lifecycle.

### ISSUE THREAD

**Issue by patrickteivas** [karlkoorna/bussiaeg#2]
Today tried to do everything according to readme, but every time got error when did `./update.sh`.
Tried on Ubuntu Desktop (18.04), Ubuntu Server (18.04) and Debian (9.8.0).
Here`s error log from npm.

```0 info it worked if it ends with ok  
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]  
2 info using npm@4.6.1  
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bussiaeg-web@3.0.8~prebuild: bussiaeg-web@3.0.8
6 silly lifecycle bussiaeg-web@3.0.8~prebuild: no script for prebuild, continuing
7 info lifecycle bussiaeg-web@3.0.8~build: bussiaeg-web@3.0.8
8 verbose lifecycle bussiaeg-web@3.0.8~build: unsafe-perm in lifecycle true
9 verbose lifecycle bussiaeg-web@3.0.8~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/bussiaeg/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle bussiaeg-web@3.0.8~build: CWD: /root/bussiaeg/web
11 silly lifecycle bussiaeg-web@3.0.8~build: Args: [ '-c', 'react-scripts build' ]
12 silly lifecycle bussiaeg-web@3.0.8~build: Returned: code: 1  signal: null
13 info lifecycle bussiaeg-web@3.0.8~build: Failed to exec build script
14 verbose stack Error: bussiaeg-web@3.0.8 build: `react-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at EventEmitter.emit (events.js:189:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:189:13)
14 verbose stack     at maybeClose (internal/child_process.js:970:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid bussiaeg-web@3.0.8
16 verbose cwd /root/bussiaeg/web
17 verbose Linux 4.15.0-45-generic
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 verbose node v10.15.1
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error bussiaeg-web@3.0.8 build: `react-scripts build`
23 error Exit status 1
24 error Failed at the bussiaeg-web@3.0.8 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]```

**Comment by karlkoorna** [comment]
Worked on my Debian machine with the same NPM and Node versions. I'm guessing you are already running `./update.sh` as root. Does manually running `npm install` then `npm run build` in `web/` work? I'd also recommend recloning the repo to see if the issue persists.

**Comment by patrickteivas** [comment]
Heretofore i tried to clone repo, but now i downloaded release and that was the solution.

**Comment by patrickteivas** [comment]
> Worked on my Debian machine with the same NPM and Node versions. I'm guessing you are already running `./update.sh` as root. Does manually running `npm install` then `npm run build` in `web/` work? I'd also recommend recloning the repo to see if the issue persists.

On `npm run build` it gave me same error.
